/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Screenshot = {
	asset?: SanityImageAssetReference;
	media?: unknown;
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	alt?: string;
	_type: 'image';
};

export type BeforeAfter = {
	_type: 'beforeAfter';
	beforeLabel?: string;
	afterLabel?: string;
	beforeContent?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	afterContent?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type PullQuote = {
	_type: 'pullQuote';
	quote?: string;
	attribution?: string;
};

export type MetricGrid = {
	_type: 'metricGrid';
	metrics?: Array<{
		value?: string;
		label?: string;
		trend?: 'up' | 'down' | 'neutral';
		_key: string;
	}>;
};

export type Callout = {
	_type: 'callout';
	variant?: 'info' | 'warn' | 'success';
	body?: string;
};

export type CodeBlock = {
	_type: 'codeBlock';
	language?:
		| 'typescript'
		| 'javascript'
		| 'svelte'
		| 'html'
		| 'css'
		| 'shell'
		| 'sql'
		| 'go'
		| 'java'
		| 'json';
	code?: string;
	filename?: string;
};

export type ImageWithCaption = {
	_type: 'imageWithCaption';
	asset?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	alt?: string;
	caption?: string;
};

export type Experiment = {
	_id: string;
	_type: 'experiment';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	hypothesis?: string;
	variantA?: {
		label?: string;
		screenshot?: Screenshot;
		copy?: string;
		material?: 'marble' | 'brass' | 'alabaster' | 'bronze';
	};
	variantB?: {
		label?: string;
		screenshot?: Screenshot;
		copy?: string;
		material?: 'marble' | 'brass' | 'alabaster' | 'bronze';
	};
	metric?: string;
	metricEvent?: string;
	postHogFlagKey?: string;
	status?: 'running' | 'concluded' | 'inconclusive';
	startDate?: string;
	endDate?: string;
	winner?: 'A' | 'B' | 'none';
	sampleSize?: number;
	summary?: string;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type TechStack = {
	_id: string;
	_type: 'techStack';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	slug?: Slug;
	category?: 'frontend' | 'backend' | 'db' | 'infra' | 'tooling' | 'lang';
	icon?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	iconName?: string;
	yearsUsed?: number;
	proficiency?: 'learning' | 'working' | 'fluent' | 'expert';
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type Post = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	excerpt?: string;
	coverImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	publishedAt?: string;
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| ({
				_key: string;
		  } & ImageWithCaption)
		| ({
				_key: string;
		  } & CodeBlock)
		| ({
				_key: string;
		  } & Callout)
		| ({
				_key: string;
		  } & MetricGrid)
		| ({
				_key: string;
		  } & PullQuote)
		| ({
				_key: string;
		  } & BeforeAfter)
	>;
	tags?: Array<string>;
	readTime?: number;
};

export type ProjectReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'project';
};

export type Testimonial = {
	_id: string;
	_type: 'testimonial';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	quote?: string;
	author?: string;
	authorRole?: string;
	authorCompany?: string;
	authorAvatar?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	featured?: boolean;
	relatedProject?: ProjectReference;
};

export type TechStackReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'techStack';
};

export type Project = {
	_id: string;
	_type: 'project';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	summary?: string;
	heroImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	gallery?: Array<{
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
		_key: string;
	}>;
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| ({
				_key: string;
		  } & ImageWithCaption)
		| ({
				_key: string;
		  } & CodeBlock)
		| ({
				_key: string;
		  } & Callout)
		| ({
				_key: string;
		  } & MetricGrid)
		| ({
				_key: string;
		  } & PullQuote)
		| ({
				_key: string;
		  } & BeforeAfter)
	>;
	metrics?: Array<{
		value?: string;
		label?: string;
		trend?: 'up' | 'down' | 'neutral';
		_key: string;
	}>;
	stack?: Array<
		{
			_key: string;
		} & TechStackReference
	>;
	role?: string;
	client?: string;
	startDate?: string;
	endDate?: string;
	featured?: boolean;
	order?: number;
	links?: Array<{
		label?: string;
		url?: string;
		type?: 'live' | 'github' | 'case-study' | 'nda';
		_key: string;
	}>;
};

export type SanityFileAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type Settings = {
	_id: string;
	_type: 'settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	availability?: 'selectively-booking' | 'fully-booked' | 'open';
	availabilityNote?: string;
	contactEmail?: string;
	socialLinks?: Array<{
		platform?: string;
		url?: string;
		_key: string;
	}>;
	resumeFile?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	heroHeadline?: string;
	heroSubheadline?: string;
	labOpeningCopy?: {
		linkedin?: string;
		github?: string;
		twitter?: string;
		default?: string;
	};
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| SanityImageAssetReference
	| Screenshot
	| BeforeAfter
	| PullQuote
	| MetricGrid
	| Callout
	| CodeBlock
	| ImageWithCaption
	| Experiment
	| SanityImageCrop
	| SanityImageHotspot
	| TechStack
	| Slug
	| Post
	| ProjectReference
	| Testimonial
	| TechStackReference
	| Project
	| SanityFileAssetReference
	| Settings
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: getFeaturedProjects
// Query: *[_type == "project" && featured == true]  | order(order asc, endDate desc)[0...3] {    ...,    stack[]->  }
export type GetFeaturedProjectsResult = Array<{
	_id: string;
	_type: 'project';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	summary?: string;
	heroImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	gallery?: Array<{
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
		_key: string;
	}>;
	body?: Array<
		| ({
				_key: string;
		  } & BeforeAfter)
		| ({
				_key: string;
		  } & Callout)
		| ({
				_key: string;
		  } & CodeBlock)
		| ({
				_key: string;
		  } & ImageWithCaption)
		| ({
				_key: string;
		  } & MetricGrid)
		| ({
				_key: string;
		  } & PullQuote)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
	>;
	metrics?: Array<{
		value?: string;
		label?: string;
		trend?: 'down' | 'neutral' | 'up';
		_key: string;
	}>;
	stack: Array<{
		_id: string;
		_type: 'techStack';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		name?: string;
		slug?: Slug;
		category?: 'backend' | 'db' | 'frontend' | 'infra' | 'lang' | 'tooling';
		icon?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		iconName?: string;
		yearsUsed?: number;
		proficiency?: 'expert' | 'fluent' | 'learning' | 'working';
	}> | null;
	role?: string;
	client?: string;
	startDate?: string;
	endDate?: string;
	featured: true;
	order?: number;
	links?: Array<{
		label?: string;
		url?: string;
		type?: 'case-study' | 'github' | 'live' | 'nda';
		_key: string;
	}>;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: getAllProjects
// Query: *[_type == "project"]  | order(coalesce(endDate, now()) desc) {    ...,    stack[]->  }
export type GetAllProjectsResult = Array<{
	_id: string;
	_type: 'project';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	summary?: string;
	heroImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	gallery?: Array<{
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
		_key: string;
	}>;
	body?: Array<
		| ({
				_key: string;
		  } & BeforeAfter)
		| ({
				_key: string;
		  } & Callout)
		| ({
				_key: string;
		  } & CodeBlock)
		| ({
				_key: string;
		  } & ImageWithCaption)
		| ({
				_key: string;
		  } & MetricGrid)
		| ({
				_key: string;
		  } & PullQuote)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
	>;
	metrics?: Array<{
		value?: string;
		label?: string;
		trend?: 'down' | 'neutral' | 'up';
		_key: string;
	}>;
	stack: Array<{
		_id: string;
		_type: 'techStack';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		name?: string;
		slug?: Slug;
		category?: 'backend' | 'db' | 'frontend' | 'infra' | 'lang' | 'tooling';
		icon?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		iconName?: string;
		yearsUsed?: number;
		proficiency?: 'expert' | 'fluent' | 'learning' | 'working';
	}> | null;
	role?: string;
	client?: string;
	startDate?: string;
	endDate?: string;
	featured?: boolean;
	order?: number;
	links?: Array<{
		label?: string;
		url?: string;
		type?: 'case-study' | 'github' | 'live' | 'nda';
		_key: string;
	}>;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: getProjectBySlug
// Query: {    "project": *[_type == "project" && slug.current == $slug][0] {      ...,      stack[]->    },    "related": *[_type == "project" && slug.current != $slug]      | order(endDate desc)[0...3] {        title,        slug,        summary,        heroImage,        role,        endDate      }  }
export type GetProjectBySlugResult = {
	project: {
		_id: string;
		_type: 'project';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		slug?: Slug;
		summary?: string;
		heroImage?: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			_type: 'image';
		};
		gallery?: Array<{
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			_type: 'image';
			_key: string;
		}>;
		body?: Array<
			| ({
					_key: string;
			  } & BeforeAfter)
			| ({
					_key: string;
			  } & Callout)
			| ({
					_key: string;
			  } & CodeBlock)
			| ({
					_key: string;
			  } & ImageWithCaption)
			| ({
					_key: string;
			  } & MetricGrid)
			| ({
					_key: string;
			  } & PullQuote)
			| {
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: 'span';
						_key: string;
					}>;
					style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
					listItem?: 'bullet' | 'number';
					markDefs?: Array<{
						href?: string;
						_type: 'link';
						_key: string;
					}>;
					level?: number;
					_type: 'block';
					_key: string;
			  }
		>;
		metrics?: Array<{
			value?: string;
			label?: string;
			trend?: 'down' | 'neutral' | 'up';
			_key: string;
		}>;
		stack: Array<{
			_id: string;
			_type: 'techStack';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			name?: string;
			slug?: Slug;
			category?: 'backend' | 'db' | 'frontend' | 'infra' | 'lang' | 'tooling';
			icon?: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
			iconName?: string;
			yearsUsed?: number;
			proficiency?: 'expert' | 'fluent' | 'learning' | 'working';
		}> | null;
		role?: string;
		client?: string;
		startDate?: string;
		endDate?: string;
		featured?: boolean;
		order?: number;
		links?: Array<{
			label?: string;
			url?: string;
			type?: 'case-study' | 'github' | 'live' | 'nda';
			_key: string;
		}>;
	} | null;
	related: Array<{
		title: string | null;
		slug: Slug | null;
		summary: string | null;
		heroImage: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			_type: 'image';
		} | null;
		role: string | null;
		endDate: string | null;
	}>;
};

// Source: src/lib/sanity/queries.ts
// Variable: getSettings
// Query: *[_type == "settings"][0]
export type GetSettingsResult = {
	_id: string;
	_type: 'settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	availability?: 'fully-booked' | 'open' | 'selectively-booking';
	availabilityNote?: string;
	contactEmail?: string;
	socialLinks?: Array<{
		platform?: string;
		url?: string;
		_key: string;
	}>;
	resumeFile?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	heroHeadline?: string;
	heroSubheadline?: string;
	labOpeningCopy?: {
		linkedin?: string;
		github?: string;
		twitter?: string;
		default?: string;
	};
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: getActiveExperiments
// Query: *[_type == "experiment" && status == "running"]  | order(startDate desc)
export type GetActiveExperimentsResult = Array<{
	_id: string;
	_type: 'experiment';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	hypothesis?: string;
	variantA?: {
		label?: string;
		screenshot?: Screenshot;
		copy?: string;
		material?: 'alabaster' | 'brass' | 'bronze' | 'marble';
	};
	variantB?: {
		label?: string;
		screenshot?: Screenshot;
		copy?: string;
		material?: 'alabaster' | 'brass' | 'bronze' | 'marble';
	};
	metric?: string;
	metricEvent?: string;
	postHogFlagKey?: string;
	status: 'running';
	startDate?: string;
	endDate?: string;
	winner?: 'A' | 'B' | 'none';
	sampleSize?: number;
	summary?: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: getConcludedExperiments
// Query: *[_type == "experiment" && status in ["concluded", "inconclusive"]]  | order(endDate desc)
export type GetConcludedExperimentsResult = Array<{
	_id: string;
	_type: 'experiment';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	hypothesis?: string;
	variantA?: {
		label?: string;
		screenshot?: Screenshot;
		copy?: string;
		material?: 'alabaster' | 'brass' | 'bronze' | 'marble';
	};
	variantB?: {
		label?: string;
		screenshot?: Screenshot;
		copy?: string;
		material?: 'alabaster' | 'brass' | 'bronze' | 'marble';
	};
	metric?: string;
	metricEvent?: string;
	postHogFlagKey?: string;
	status?: 'concluded' | 'inconclusive' | 'running';
	startDate?: string;
	endDate?: string;
	winner?: 'A' | 'B' | 'none';
	sampleSize?: number;
	summary?: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: getAllPosts
// Query: *[_type == "post"]  | order(publishedAt desc) {    title,    slug,    excerpt,    coverImage,    publishedAt,    readTime,    tags  }
export type GetAllPostsResult = Array<{
	title: string | null;
	slug: Slug | null;
	excerpt: string | null;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	} | null;
	publishedAt: string | null;
	readTime: number | null;
	tags: Array<string> | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: getPostBySlug
// Query: *[_type == "post" && slug.current == $slug][0]
export type GetPostBySlugResult = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	excerpt?: string;
	coverImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	publishedAt?: string;
	body?: Array<
		| ({
				_key: string;
		  } & BeforeAfter)
		| ({
				_key: string;
		  } & Callout)
		| ({
				_key: string;
		  } & CodeBlock)
		| ({
				_key: string;
		  } & ImageWithCaption)
		| ({
				_key: string;
		  } & MetricGrid)
		| ({
				_key: string;
		  } & PullQuote)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
	>;
	tags?: Array<string>;
	readTime?: number;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: getTestimonials
// Query: *[_type == "testimonial" && ($featured == null || featured == $featured)]  | order(_createdAt desc)
export type GetTestimonialsResult = Array<{
	_id: string;
	_type: 'testimonial';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	quote?: string;
	author?: string;
	authorRole?: string;
	authorCompany?: string;
	authorAvatar?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	featured?: boolean;
	relatedProject?: ProjectReference;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: getAllTechStacks
// Query: *[_type == "techStack"]  | order(category asc, proficiency desc) {    _id,    name,    category,    proficiency,    yearsUsed,    iconName  }
export type GetAllTechStacksResult = Array<{
	_id: string;
	name: string | null;
	category: 'backend' | 'db' | 'frontend' | 'infra' | 'lang' | 'tooling' | null;
	proficiency: 'expert' | 'fluent' | 'learning' | 'working' | null;
	yearsUsed: number | null;
	iconName: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'\n  *[_type == "project" && featured == true]\n  | order(order asc, endDate desc)[0...3] {\n    ...,\n    stack[]->\n  }\n': GetFeaturedProjectsResult;
		'\n  *[_type == "project"]\n  | order(coalesce(endDate, now()) desc) {\n    ...,\n    stack[]->\n  }\n': GetAllProjectsResult;
		'\n  {\n    "project": *[_type == "project" && slug.current == $slug][0] {\n      ...,\n      stack[]->\n    },\n    "related": *[_type == "project" && slug.current != $slug]\n      | order(endDate desc)[0...3] {\n        title,\n        slug,\n        summary,\n        heroImage,\n        role,\n        endDate\n      }\n  }\n': GetProjectBySlugResult;
		'\n  *[_type == "settings"][0]\n': GetSettingsResult;
		'\n  *[_type == "experiment" && status == "running"]\n  | order(startDate desc)\n': GetActiveExperimentsResult;
		'\n  *[_type == "experiment" && status in ["concluded", "inconclusive"]]\n  | order(endDate desc)\n': GetConcludedExperimentsResult;
		'\n  *[_type == "post"]\n  | order(publishedAt desc) {\n    title,\n    slug,\n    excerpt,\n    coverImage,\n    publishedAt,\n    readTime,\n    tags\n  }\n': GetAllPostsResult;
		'\n  *[_type == "post" && slug.current == $slug][0]\n': GetPostBySlugResult;
		'\n  *[_type == "testimonial" && ($featured == null || featured == $featured)]\n  | order(_createdAt desc)\n': GetTestimonialsResult;
		'\n  *[_type == "techStack"]\n  | order(category asc, proficiency desc) {\n    _id,\n    name,\n    category,\n    proficiency,\n    yearsUsed,\n    iconName\n  }\n': GetAllTechStacksResult;
	}
}
